DROP FUNCTION UNIV.DISPLAY_CURSO_ALN
GO
CREATE FUNCTION UNIV.DISPLAY_CURSO_ALN (@NUMERO INTEGER) RETURNS Table 
AS
RETURN (
    SELECT DATA_INICIO, DATA_FIM, NOME, TIPO, CODIGO 
    FROM UNIV.Aluno
    JOIN UNIV.Pert_Curso ON NUMERO=CODIGO_ALUNO
    JOIN UNIV.Curso ON CODIGO_CURSO=CODIGO
    WHERE CODIGO_ALUNO=@NUMERO
)
GO
