
-- USAR PARA FAZER A TABELA DAS PESSOAS
DROP VIEW UNIV.DISPLAY_FUNC
GO
CREATE VIEW UNIV.DISPLAY_FUNC AS
    SELECT Pessoa.CC, NIF, Pessoa.NOME, NUMERO, FUNCAO, ID_TRAB, ENDEREÇO, Local_Trabalho.NOME AS NOME_TRAB
    FROM UNIV.Funcionario JOIN UNIV.Pessoa 
    ON Pessoa.CC=Funcionario.CC
    JOIN UNIV.Local_Trabalho ON ID_TRAB=Local_Trabalho.ID
GO

DROP VIEW UNIV.DISPLAY_DOC
GO
CREATE VIEW UNIV.DISPLAY_DOC AS
    SELECT Pessoa.CC, NIF, Pessoa.NOME, TELEFONE, Docente.ID_DEP, REF_PROJETO, Curso.NOME AS NOME_CURSO, TIPO, CODIGO
    FROM UNIV.Docente JOIN UNIV.Pessoa ON Pessoa.CC=Docente.CC
    LEFT JOIN UNIV.Curso ON Pessoa.CC=CC_DIRETOR
GO

DROP VIEW UNIV.DISPLAY_INV
GO
CREATE VIEW UNIV.DISPLAY_INV AS
    SELECT Pessoa.CC, NIF, NOME, TELEFONE, ID_DEP, REF_PROJETO 
    FROM UNIV.Investigador JOIN UNIV.Pessoa 
    ON Pessoa.CC=Investigador.CC
GO

DROP VIEW UNIV.DISPLAY_ALN
GO
CREATE VIEW UNIV.DISPLAY_ALN AS
    SELECT Pessoa.CC, NIF, Pessoa.NOME, NUMERO, ANO, N_MATRICULAS, REF_PROJETO
    FROM UNIV.Aluno JOIN UNIV.Pessoa ON Pessoa.CC=Aluno.CC
GO



-- SELECT * FROM UNIV.DISPLAY_CURSO_ALN(91234)
-- SELECT * FROM UNIV.DISPLAY_FUNC
-- SELECT * FROM UNIV.DISPLAY_INV
-- SELECT * FROM UNIV.DISPLAY_DOC
-- SELECT * FROM UNIV.DISPLAY_ALN
GO


-- USAR PARA FAZER A TABELA DOS LUGARES

DROP VIEW UNIV.DISPLAY_REIT
GO
CREATE VIEW UNIV.DISPLAY_REIT AS
    SELECT Local_Trabalho.ID, ENDEREÇO, NOME, NOME_UNIV
    FROM UNIV.Reitoria JOIN UNIV.Local_Trabalho
    ON Reitoria.ID=Local_Trabalho.ID
GO

DROP VIEW UNIV.DISPLAY_CAMPUS
GO
CREATE VIEW UNIV.DISPLAY_CAMPUS AS
    SELECT Local_Trabalho.ID, ENDEREÇO, NOME
    FROM UNIV.Campus JOIN UNIV.Local_Trabalho
    ON Campus.ID=Local_Trabalho.ID
GO

DROP VIEW UNIV.DISPLAY_DEP
GO
CREATE VIEW UNIV.DISPLAY_DEP AS
    SELECT Local_Trabalho.ID, ENDEREÇO, NOME, TELEFONE, HORARIO, BAR
    FROM UNIV.Departamento JOIN UNIV.Local_Trabalho
    ON Departamento.ID=Local_Trabalho.ID
GO

-- SELECT * FROM UNIV.DISPLAY_REIT
-- SELECT * FROM UNIV.DISPLAY_CAMPUS
-- SELECT * FROM UNIV.DISPLAY_DEP

DROP VIEW UNIV.DISPLAY_CURSO
GO
CREATE VIEW UNIV.DISPLAY_CURSO AS
    SELECT Curso.CODIGO, CC_DIRETOR, NOME, TIPO, ID_DEP FROM UNIV.Curso
GO


